---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь мобильную версию
implicit:
  - Сайт должен иметь регистрационную форму с данными покупателя для связи
  - Сайт должен иметь страницу оплаты
  - Пользователь должен иметь возможность продолжать покупки без потери товаров в корзине
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен иметь возможность размещать заказ
